apiVersion: apps/v1
kind: Deployment
metadata:
  name: product-service
spec:
  replicas: 1
  selector:
    matchLabels:
      app: product-service
  template:
    metadata:
      labels:
        app: product-service
    spec:
      containers:
        - name: product-service
          image: murphshi/devops-product-service:IMAGE_TAG
          ports:
            - containerPort: 3001
          resources:
            requests:
              cpu: "250m"
              memory: "256Mi"
            limits:
              cpu: "500m"
              memory: "512Mi"
          env:
            - name: DB_HOST
              value: "database"
            - name: DB_NAME
              value: "ecommerce"
            - name: DB_USER
              value: "postgres"
            - name: DB_PASSWORD
              value: "password"
            - name: PORT
              value: "3001"